//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP02_GARAGE.Model.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voiture
    {
        public int IdVoiture { get; set; }
        public string Matricule { get; set; }
        public string MotifPanne { get; set; }
        public string EstVoitureDeSociete { get; set; }
        public string ImageVoiture { get; set; }
        public Nullable<System.DateTime> DateEntree { get; set; }
        public string Info { get; set; }
    }
}
